### ISSUE TITLE
Character literals below 8 are broken

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1602]
I encountered this problem in PSCi:

```
> '\7'
/.../.psci_modules/node_modules/$PSCI/index.js:5
var it = "\x7";
         ^^^^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/taylor/Documents/Code/purescript-neon/.psci_modules/index.js:1:63)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)

> '\8'
'
```

But it also happens with plain PSC.

``` purescript
module Main where
x :: Char
x = '\7'
```

``` javascript
// Generated by psc version 0.7.5.3
"use strict";
var x = "\x7";
module.exports = {
    x: x
};
```

```
/.../output/Main/index.js:3
var x = "\x7";
        ^^^^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/private/var/folders/lw/f0zrsxbj1t9gc25wtx1ljbd80000gn/T/pulp-run115101-74174-1b5s11r.js:1:63)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

**Comment by michaelficarra** [comment]
It should be a problem for all escapes below 16 (0x10). I believe the issue  is here: https://github.com/purescript/purescript/blob/688fc66c27cfd4d8505cd11006a9eac6b55e1f31/src/Language/PureScript/Pretty/JS.hs#L171

I can fix this in a few days when I'm back in front of my computer, but feel free to do so before then.
