### ISSUE TITLE
Type Checker bug

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript/purescript#1636]
This program compiles just fine:

https://gist.github.com/kRITZCREEK/81c4fc70b90938a7aadc

```purescript
module Main where

import Control.Monad.Eff.Console
import Data.Lens
import Data.List
import Data.Maybe (Maybe(..), fromMaybe)
import Prelude

main = log <<< show $ prettyWorld testWorld

newtype Location = Location {x :: Int , y :: Int}
newtype World    = World (List Location)

_x :: LensP Location Int
_x = lens (\(Location l) -> l.x) (\(Location l) newX -> Location (l { x=newX }))

_y :: LensP Location Int
_y = lens (\(Location l) -> l.y) (\(Location l) newY -> Location (l { y=newY }))

_locations :: IsoP World (List Location)
_locations = iso (\(World l) -> l) World

loc x y = Location {x: x, y: y}

testWorld :: World
testWorld = World (toList [loc 1 1, loc 2 2, loc 3 3])

prettyWorld :: World -> Int
prettyWorld w = maxX
  where
    onLocations selector = w ^.. _locations <<< traversed <<< selector
    foldOnLocations folder selector = fromMaybe 0 (folder traversed (onLocations selector))
    maxX = foldOnLocations maximumOf _x
```

dependencies:
 - purescript-console
 - purescript-lists
 - purescript-profunctor-lenses

but when run errors with:

```
/home/creek/Documents/game-of-life/output/Data.Lens.Traversal/index.js:14
        return Data_Lens_Internal_Wander.wander(__dict_Wander_1)(function (__dict_Applicative_2) {
                                                                ^

TypeError: Data_Lens_Internal_Wander.wander(...) is not a function
    at /home/creek/Documents/game-of-life/output/Data.Lens.Traversal/index.js:14:65
    at /home/creek/Documents/game-of-life/output/Data.Lens.Fold/index.js:79:69
    at /home/creek/Documents/game-of-life/output/Data.Lens.Fold/index.js:102:19
    at /home/creek/Documents/game-of-life/output/Main/index.js:78:108
    at prettyWorld (/home/creek/Documents/game-of-life/output/Main/index.js:81:73)
    at Object.<anonymous> (/home/creek/Documents/game-of-life/output/Main/index.js:84:72)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
* ERROR: Subcommand terminated with error code 1

```

**Comment by garyb** [comment]
Looks related to #1595 or #1594 - a problem with re-exports and codegen.

**Comment by paf31** [comment]
Really? Could that cause an "is not a function" error?

**Comment by garyb** [comment]
Oh, hmm. Maybe not actually. I didn't read the error closely enough and assumed that `Data_Lens_Internal_Wander` wasn't in scope and is therefore `undefined` - but it's getting past that and applying `wander(...)`. Apparently `__dict_Wander_1` isn't a Wander dictionary then?

**Comment by paf31** [comment]
I assume this is an elaboration issue in the type checker, but I'll have a look and see.
