### ISSUE TITLE
Runtime Type Error when defining data constructor with the same name as a type in another file

### ISSUE THREAD

**Issue by soupi** [purescript/purescript#1706]
for example, run `pulp init` and add these files to the src folder:

Main.purs:

```purs
module Main where

import Bug 

main = do
  action buggy

data Buggy
  = Bug Bug
```

Bug.purs:

```purs
module Bug where

import Prelude
import Control.Monad.Eff
import Control.Monad.Eff.Console

type Bug = { str :: String }

buggy :: Bug 
buggy = { str:  "bug" }

action :: Bug -> Eff _ Unit
action b = do
  log b.str
  pure unit
```

Result:

```sh
➜  bug  pulp run  
* Building project in /Users/suppi/code/purescript/bug
psc: No files found using pattern: src/**/*.js
* Build successful.
/Users/suppi/code/purescript/bug/output/Main/index.js:13
var main = Bug.action(Bug.buggy);
               ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/suppi/code/purescript/bug/output/Main/index.js:13:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/private/var/folders/bl/1z7yj51d295966jmb9x2_n7r0000gn/T/pulp-run1151112-2972-1wfq2ka.js:1:63)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
* ERROR: Subcommand terminated with error code 1
```

**Comment by paf31** [comment]
@garyb This was fixed at one point, right? Didn't we start renaming things?

**Comment by garyb** [comment]
Yeah, it's fixed _now_ actually, just not in 0.7.6.1.

**Comment by garyb** [comment]
@soupi the error is actually occurring because of the module and type being named the same thing, by the way, not a collision between type names.

**Comment by soupi** [comment]
@garyb you mean in `Bug.purs`?

**Comment by garyb** [comment]
Actually, what I said isn't quite right, I meant between the data constructor and module here. So in `main`, the generated code will have:

```
var Bug = require("Bug");
```

for the module import, and then it'll also have

```
var Bug = (function () {
 ...
})();
```

for the `Bug` data constructor of `Buggy`. So `Bug.action` in `main` which should be referring to the module import `Bug` will actually be referring to the constructor.

It's fixed in `master`.

**Comment by soupi** [comment]
@garyb alright. that makes sense, i'm glad it's fixed :)

**Comment by paf31** [comment]
Sorry for the confusion, I didn't realize this was fixed so recently.
