### ISSUE TITLE
Runtime error with re-exported type classes

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript#1716]
This program:
```purescript
module Main where

import Prelude
import Control.Monad.Eff
import Control.Monad.Eff.Console
import Control.Monad.Except.Trans

main :: Eff _ Unit
main = log "hello world"

newtype Lol m a = Lol (m a)

instance lolTrans :: MonadTrans Lol where
  lift = Lol
```
Fails at runtime with:
```
/home/harry/documents/code/ps-scratch/output/Main/index.js:11
var lolTrans = new Control_Monad_Trans.MonadTrans(function (__dict_Monad_0) {
                   ^

ReferenceError: Control_Monad_Trans is not defined
    at Object.<anonymous> (/home/harry/documents/code/ps-scratch/output/Main/index.js:11:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/pulp-run1151115-31919-qzgvrl.js:1:63)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

I think this may be because `Control.Monad.Except.Trans` re-exports `Control.Monad.Trans`.

Also, if you import `Control.Monad.Trans`, you get a warning about that import being redundant, but it works.

**Comment by garyb** [comment]
Is this using `master`? If not, yeah, it should be fixed in `master`.

**Comment by garyb** [comment]
#1595

**Comment by hdgarrood** [comment]
No, 0.7.6.1. That looks like it's probably it, I'l check.

**Comment by hdgarrood** [comment]
Yep, this works as expected in master.

**Comment by garyb** [comment]
Phew :smile:

**Comment by garyb** [comment]
This is the issue blocking purescript/purescript-transformers#62 too, by the way.
