### ISSUE TITLE
Linux npm installation failure

### ISSUE THREAD

**Issue by raould** [purescript/purescript#1944]
Ubuntu 14.04 LTS x86 (not 64 bit).
superman@superlap4300:~/Dev/Purescript$ uname -a
Linux superlap4300 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:28:32 UTC 2016 i686 i686 i686 GNU/Linux
superman@superlap4300:~/Dev/Purescript$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
superman@superlap4300:~/Dev/Purescript$ cabal --version
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library 

```
superman@superlap4300:~/Dev/Purescript$ npm install -g purescript
/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/bin/psc -> /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/bin/psc.js
/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/bin/psci -> /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/bin/psci.js
/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/bin/psc-bundle -> /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/bin/psc-bundle.js
/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/bin/psc-docs -> /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/bin/psc-docs.js
/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/bin/psc-publish -> /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/bin/psc-publish.js

> purescript@0.8.2 postinstall /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript
> node --harmony_destructuring lib/install.js

  ⚠ The `/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/psc` binary doesn't seem to work correctly
  ⚠ psc pre-build test failed
  ℹ compiling from source
  ✖ Error: cabal sandbox init --sandbox="/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/.cabal-sandbox" && cabal update && cabal install --bindir /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor --jobs=2
Command failed: /bin/sh -c cabal install --bindir /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor --jobs=2
cabal:
/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/.cabal-sandbox/logs/stm-2.4.4.1.log:
does not exist

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  ⚠ The `/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/psc-bundle` binary doesn't seem to work correctly
  ⚠ psc-bundle pre-build test failed
  ℹ compiling from source
  ✖ Error: cabal sandbox init --sandbox="/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/.cabal-sandbox" && cabal update && cabal install --bindir /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor --jobs=2
Command failed: /bin/sh -c cabal install --bindir /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor --jobs=2
cabal:
/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/.cabal-sandbox/logs/stm-2.4.4.1.log:
does not exist

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  ⚠ The `/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/psc-docs` binary doesn't seem to work correctly
  ⚠ psc-docs pre-build test failed
  ℹ compiling from source
  ✖ Error: cabal sandbox init --sandbox="/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/.cabal-sandbox" && cabal update && cabal install --bindir /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor --jobs=2
Command failed: /bin/sh -c cabal install --bindir /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor --jobs=2
cabal:
/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/.cabal-sandbox/logs/stm-2.4.4.1.log:
does not exist

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  ⚠ The `/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/psc-publish` binary doesn't seem to work correctly
  ⚠ psc-publish pre-build test failed
  ℹ compiling from source
  ✖ Error: cabal sandbox init --sandbox="/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/.cabal-sandbox" && cabal update && cabal install --bindir /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor --jobs=2
Command failed: /bin/sh -c cabal install --bindir /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor --jobs=2
cabal:
/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/.cabal-sandbox/logs/stm-2.4.4.1.log:
does not exist

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  ⚠ The `/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/psci` binary doesn't seem to work correctly
  ⚠ psci pre-build test failed
  ℹ compiling from source
  ✖ Error: cabal sandbox init --sandbox="/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/.cabal-sandbox" && cabal update && cabal install --bindir /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor --jobs=2
Command failed: /bin/sh -c cabal install --bindir /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor --jobs=2
cabal:
/home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript/vendor/.cabal-sandbox/logs/stm-2.4.4.1.log:
does not exist

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
purescript@0.8.2 /home/superman/Dev/NodeJS/node-v4.2.2-linux-x86/lib/node_modules/purescript
├── async-each-series@1.1.0
├── to-executable-name@1.1.0
├── logalot@2.1.0 (figures@1.4.0, squeak@1.3.0)
├── bin-wrapper@3.0.2 (lazy-req@1.1.0, os-filter-obj@1.0.3, each-async@1.1.1, bin-check@2.0.0, bin-version-check@2.1.0, download@4.4.3)
└── bin-build@2.2.0 (exec-series@1.0.2, url-regex@3.1.0, tempfile@1.1.1, archive-type@3.2.0, rimraf@2.5.2, decompress@3.0.0, download@4.4.3)
superman@superlap4300:~/Dev/Purescript$ psc
/usr/local/lib/node_modules/purescript/vendor/psc: 1: /usr/local/lib/node_modules/purescript/vendor/psc: Syntax error: word unexpected (expecting ")")
```

**Comment by paf31** [comment]
Please file this on the npm package repo.

**Comment by hdgarrood** [comment]
That's https://GitHub.com/purescript-contrib/node-purescript-bin IIRC.
