### ISSUE TITLE
sudo npm install -g purescript fails on FreeBSD

### ISSUE THREAD

**Issue by roman-neuhauser** [purescript/purescript#2463]
1. http://www.purescript.org/learn/getting-started/ fails to state the dependency on stack
2. installation fails even after `sudo pkg install stack`, obviously with a different error:

```
roman@sheeba ~ master :M 0 1001 0 . sudo npm install -g purescript 
/usr/local/bin/psc-bundle -> /usr/local/lib/node_modules/purescript/bin/psc-bundle.js
/usr/local/bin/psc -> /usr/local/lib/node_modules/purescript/bin/psc.js
/usr/local/bin/psc-docs -> /usr/local/lib/node_modules/purescript/bin/psc-docs.js
/usr/local/bin/psc-ide-client -> /usr/local/lib/node_modules/purescript/bin/psc-ide-client.js
/usr/local/bin/psc-ide-server -> /usr/local/lib/node_modules/purescript/bin/psc-ide-server.js
/usr/local/bin/psc-package -> /usr/local/lib/node_modules/purescript/bin/psc-package.js
/usr/local/bin/psc-publish -> /usr/local/lib/node_modules/purescript/bin/psc-publish.js
/usr/local/bin/psci -> /usr/local/lib/node_modules/purescript/bin/psci.js

> purescript@0.10.2 postinstall /usr/local/lib/node_modules/purescript
> node lib/install.js

  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-bundle pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-docs pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-ide-client pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-ide-server pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-package pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psc-publish pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ psci pre-build test failed
  ℹ compiling from source
  ✖ Error: stack setup && stack install --local-bin-path /usr/local/lib/node_modules/purescript/vendor
Command failed: stack setup
Preventing creation of stack root '/root/.stack/'. Parent directory '/root/' is owned by someone else.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
/usr/local/lib
└─┬ purescript@0.10.2 
...
```

```
roman@sheeba ~ master :M 0 1002 0 . pulp psci
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/lib/node_modules/purescript/vendor/psc ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
* ERROR: Subcommand terminated with exit code 1
```

**Comment by michaelficarra** [comment]
Try `sudo su root -c 'npm install -g purescript'`.

**Comment by paf31** [comment]
If this does turn out to be a bug, please report it on the `node-purescript-bin` repo. Thanks!

**Comment by roman-neuhauser** [comment]
what about the the documentation problem (unstated dependency on stack)?  where should i report that?

**Comment by garyb** [comment]
Same place :). Anything that happens during `npm install purescript` is due to the `npm` package, not the compiler itself.

**Comment by hdgarrood** [comment]
@roman-neuhauser: sorry that you're being sent all over the place, we're just trying to keep our issue trackers clean. We're in a bit of a transition period with documentation right now, which makes it a little difficult to say where issues should go, but documentation problems should be addressed at https://github.com/purescript/documentation and/or https://github.com/purescript/purescript.github.io. Don't worry about opening any more issues though, I'll make a note to address this myself.
