### ISSUE TITLE
Currification Bug: "f a = expr a"  does not behave like  "f = expr"

### ISSUE THREAD

**Issue by rvion** [purescript/purescript#2485]
Currification Bug: "f a = expr a" does  not behave like  "f = expr"

```js
var Main = require("./output/Demo/index.js");
Main.main()
```

# case 1 : CRASH

```purescript
module Demo where

import Prelude
import Control.Monad.Eff.Console (log)
import Data.Maybe (fromMaybe)
import Partial.Unsafe (unsafeCrashWith)

main = log "ok"

-- unsafeFromMaybe1 mba = fromMaybe (unsafeCrashWith "error 1") mba
unsafeFromMaybe2     = fromMaybe (unsafeCrashWith "error 2")
```

```shell
$ node main.js
/Users/rvion/dev/advent-of-code/output/Partial/foreign.js:7
    throw new Error(msg);
    ^

Error: error 2
    at /Users/rvion/dev/advent-of-code/output/Partial/foreign.js:7:11
    at /Users/rvion/dev/advent-of-code/output/Partial.Unsafe/index.js:7:46
    at Object.exports.unsafePartial (/Users/rvion/dev/advent-of-code/output/Partial.Unsafe/foreign.js:6:10)
    at Object.unsafeCrashWith (/Users/rvion/dev/advent-of-code/output/Partial.Unsafe/index.js:6:21)
    at Object.<anonymous> (/Users/rvion/dev/advent-of-code/output/Demo/index.js:10:60)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

📝  I don't even call `unsafeCrashWith` in the code

# case 2 : NO crash

```purescript
module Demo where

import Prelude
import Control.Monad.Eff.Console (log)
import Data.Maybe (fromMaybe)
import Partial.Unsafe (unsafeCrashWith)

main = log "ok"

unsafeFromMaybe1 mba = fromMaybe (unsafeCrashWith "error 1") mba
-- unsafeFromMaybe2     = fromMaybe (unsafeCrashWith "error 2")
```

```shell
$ node main.js
ok
```

----------

```
psc --version
0.10.2
```

**Comment by rvion** [comment]
also: 🔴 
```purescript
unsafeFromMaybe1 mba = fromMaybe (unsafeCrashWith "error 1") mba
```

crash uppon using.

-------------------


both 

```purescript
unsafeFromMaybe :: forall a. Maybe a -> a
unsafeFromMaybe mba = case mba of
  Nothing -> unsafeCrashWith "maybe was not a just"
  Just a -> a
```

and 

```purescript
unsafeFromMaybe :: forall a. Maybe a -> a
unsafeFromMaybe = case _ of
  Nothing -> unsafeCrashWith "maybe was not a just"
  Just a -> a
```

works, though 🍏

**Comment by garyb** [comment]
Not a bug, these can be summed up as: PureScript isn't lazy.

By eta-expanding `unsafeFromMaybe1` you're prevening the evaulation of  `unsafeCrashWith` until the `mba` argument is provided. Also, it is called `unsafeCrashWith` for a reason. :) This doesn't apply to normally effectful code because it is not evaluated until `bind`, which is part of what makes `unsafeCrashWith` unsafe.

**Comment by LiamGoodacre** [comment]
There is also `crashWith` which won't explode until you discharge the `Partial` constraint.  This is really the same thing as eta-expanding; because constraints are encoded as function arguments, and `unsafePartial` calls the function.

**Comment by LiamGoodacre** [comment]
An alternative way to write it could be:

```purescript
unsafeFromMaybe = unsafePartial <<< fromMaybe (crashWith "error 1")
```

Which also won't explode until called.

**Comment by rvion** [comment]
thanks for the feedback :)
