### ISSUE TITLE
Install via npm fails

### ISSUE THREAD

**Issue by CarstenKoenig** [purescript/purescript#3668]
version 0.13 is on npm but when I try to `npm install -g purescript` I get the following error:

```
$ npm install -g purescript
.../.npm/bin/purs -> .../.npm/lib/node_modules/purescript/purs.bin

> purescript@0.13.0 postinstall .../.npm/lib/node_modules/purescript
> install-purescript --purs-ver=0.13.0

.../.npm/lib/node_modules/purescript/node_modules/install-purescript-cli/index.js:97
	} catch {
	        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! purescript@0.13.0 postinstall: `install-purescript --purs-ver=0.13.0`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the purescript@0.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

same is happening if I try to install it into an existing project `npm install --save-dev purescript`

----

System: Linux / node v8.16.0 / npm 6.4.1

**Comment by garyb** [comment]
Please open issues about the npm package on https://github.com/purescript-contrib/node-purescript

This is down to an old version of node however 🙂

**Comment by CarstenKoenig** [comment]
ok sorry :(
