### ISSUE TITLE
Runtime error "TypeError: v is not a function" for recursively defined Reader.

### ISSUE THREAD

**Issue by sureyeaah** [purescript/purescript#3798]
This recursively defined Reader compiles but leads to a runtime error when run.
```PureScript
foo :: Reader Int String
foo = do
  val <- asks identity
  case val of
    0 -> pure "done"
    _ -> decFoo
  where
    decFoo = (\_ -> local (_ - 1) foo) unit
```
Letting `decFoo` be a suspended computation and calling it with `unit` inside do works fine.

```
/output/Control.Monad.Reader.Trans/index.js:32
            return v(f($66));
                   ^

TypeError: v is not a function
    at /output/Control.Monad.Reader.Trans/index.js:32:20
    at /output/Control.Monad.Reader.Trans/index.js:102:28
    at /output/Data.Identity/index.js:211:16
    at /output/Control.Monad.Reader.Trans/index.js:100:57
    at /output/Control.Monad.Reader/index.js:10:19
    at Object.__do [as main] (/output/Test.Main/index.js:29:48)
    at Object.<anonymous> (/.spago/run.js:3:34)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
```

**Comment by natefaubion** [comment]
It's not possible for the compiler to locally determine if an application yields to a strict recursive reference in general. It could only check it for pedagogical cases like `unit` application, so we don't bother. See #2113
