### ISSUE TITLE
install with yarn on void linux musl

### ISSUE THREAD

**Issue by gasacchi** [purescript/purescript#3988]
## Description

I want to try purescript, and try to install on my void linux musl with yarn and get error instead

## To Reproduce

Steps to reproduce the behavior.
```
yarn global add purescript
```
output:
```
Command: install-purescript --purs-ver=0.13.8
Arguments: 
Directory: /home/gasacchi/.config/yarn/global/node_modules/purescript
Output:
[ SUCCESS ] Check if a prebuilt 0.13.8 binary is provided for linux (4s)
[ SUCCESS ] Download the prebuilt PureScript binary (55s)
[ FAILURE ] Verify the prebuilt binary works correctly
Error: spawn /home/gasacchi/xxx/.dev/gsclinux/.config/yarn/global/node_modules/purescript/purs.bin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

↓ Fallback: building from source

[ FAILURE ] Check if 'stack' command is available
Error: Command failed with exit code 2 (ENOENT): stack --allow-different-user --numeric-version
spawn stack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```
## Expected behavior

purescript success installed
## Additional context

running on Void linux with musl libc
## PureScript version

0.13.8

**Comment by purefunctor** [comment]
The provided binaries don't seem to be compatible with your system, which ultimately causes it to fall back to building from source that requires [stack](https://docs.haskellstack.org/en/stable/README/). In my Arch system I had to install ncurses5-compat-libs although I'm not sure if that applies here; could always try building from source though.

**Comment by hdgarrood** [comment]
Yes, the Linux binaries we provide won’t work on non-glibc-based systems. You’ll need to build the compiler from source, which requires stack.

**Comment by gasacchi** [comment]
i got error when use ```stack install```
```
Preparing to install GHC (tinfo6) to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-tinfo6-8.6.5.                                      
utils/ghc-cabal/dist-install/build/tmp/ghc-cabal-bindist: 3: exec: utils/ghc-cabal/dist-install/build/tmp/ghc-cabal: not found
make[1]: *** [ghc.mk:990: install_packages] Error 127
make: *** [Makefile:51: install] Error 2
Received ExitFailure 2 when running
Raw command: /bin/make install
Run from: /home/gasacchi/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5.temp/ghc-8.6.5/

                  
Error: Error encountered while installing GHC with
         make install
         run in /home/gasacchi/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5.temp/ghc-8.6.5/
       
       The following directories may now contain files, but won't be used by stack:
         - /home/gasacchi/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5.temp/
         - /home/gasacchi/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/
       
       For more information consider rerunning with --verbose flag
       
Installing GHC ..
```

**Comment by hdgarrood** [comment]
I'd suggest having a look on stack's issue tracker to see if you can find anyone else in a similar situation to you; maybe stack doesn't support non-glibc-based systems so well.
