### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by WilliamBehrens** [purescript/purescript#4029]
## Description
Error when trying to install purescript on archlinux using both npm and yarn

npm install -g purescript
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/pixtum/.npm-global/lib/node_modules/purescript
npm ERR! command failed
npm ERR! command sh -c install-purescript --purs-ver=0.14.0
npm ERR! [ SUCCESS ] Check if a prebuilt 0.14.0 binary is provided for linux (467ms)
npm ERR! [ SUCCESS ] Download the prebuilt PureScript binary (555ms)
npm ERR! [ FAILURE ] Verify the prebuilt binary works correctly
npm ERR! Error: Command failed: /home/pixtum/.npm-global/lib/node_modules/purescript/purs.bin --version
npm ERR! /home/pixtum/.npm-global/lib/node_modules/purescript/purs.bin: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
npm ERR!
npm ERR!     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR!     at ChildProcess.emit (node:events:378:20)
npm ERR!     at maybeClose (node:internal/child_process:1067:16)
npm ERR!     at Socket.<anonymous> (node:internal/child_process:453:11)
npm ERR!     at Socket.emit (node:events:378:20)
npm ERR!     at Pipe.<anonymous> (node:net:665:12)
npm ERR!
npm ERR! ↓ Fallback: building from source
npm ERR!
npm ERR! [ SUCCESS ] Check if 'stack' command is available
npm ERR! [ SUCCESS ] Download the PureScript 0.14.0 source (881ms)
npm ERR! [ RUNNING ] command: stack setup
npm ERR!   Specified file "README.md" for extra-source-files does not exist
npm ERR!   Specified file "INSTALL.md" for extra-source-files does not exist
npm ERR!   Specified file "CONTRIBUTORS.md" for extra-source-files does not exist
npm ERR!   Specified file "CONTRIBUTING.md" for extra-source-files does not exist
npm ERR!   Specified file "README.md" for extra-source-files does not exist
npm ERR!   Specified file "README.md" for extra-source-files does not exist
npm ERR!   stack will use a sandboxed GHC it installed
npm ERR!   For more information on paths, see 'stack path' and 'stack exec env'
npm ERR!   To use this GHC and packages outside of a project, consider using:
npm ERR!   stack ghc, stack ghci, stack runghc, or stack exec
npm ERR! [ SUCCESS ] Ensure the appropriate GHC is installed (1s)
npm ERR! [ RUNNING ] command: stack install --local-bin-path=/home/pixtum/.npm-global/lib/node_modules/purescript --flag=purescript:RELEASE
npm ERR!   Specified file "README.md" for extra-source-files does not exist
npm ERR!   Specified file "INSTALL.md" for extra-source-files does not exist
npm ERR!   Specified file "CONTRIBUTORS.md" for extra-source-files does not exist
npm ERR!   Specified file "CONTRIBUTING.md" for extra-source-files does not exist
npm ERR!   Specified file "README.md" for extra-source-files does not exist
npm ERR!   Specified file "README.md" for extra-source-files does not exist
npm ERR!   purescript-ast     > configure (lib)
npm ERR!   purescript-ast     > Configuring purescript-ast-0.1.0.0...
npm ERR!   language-javascript> configure
npm ERR!   purescript-ast     > build (lib)
npm ERR!   purescript-ast     > Preprocessing library for purescript-ast-0.1.0.0..
npm ERR!   purescript-ast     > Building library for purescript-ast-0.1.0.0..
npm ERR!   purescript-ast     > [ 1 of 22] Compiling Control.Monad.Supply
npm ERR!   purescript-ast     > [ 2 of 22] Compiling Control.Monad.Supply.Class
npm ERR!   language-javascript> Configuring language-javascript-0.7.0.0...
npm ERR!   purescript-ast     > [ 3 of 22] Compiling Language.PureScript.Comments
npm ERR!   language-javascript> build
npm ERR!   language-javascript> Preprocessing library for language-javascript-0.7.0.0..
npm ERR!   language-javascript> happy: src/Language/JavaScript/Parser/Grammar7.y: hGetContents: invalid argument (invalid byte sequence)
npm ERR!   purescript-ast     > [ 4 of 22] Compiling Language.PureScript.AST.SourcePos
npm ERR!   purescript-ast     > [ 5 of 22] Compiling Language.PureScript.Crash
npm ERR!   purescript-ast     > [ 6 of 22] Compiling Language.PureScript.AST.Operators
npm ERR!   purescript-ast     > [ 7 of 22] Compiling Language.PureScript.Names
npm ERR!   purescript-ast     > [ 8 of 22] Compiling Language.PureScript.Constants.Prim
npm ERR!   purescript-ast     > [ 9 of 22] Compiling Language.PureScript.PSString
npm ERR!   purescript-ast     > [10 of 22] Compiling Language.PureScript.Label
npm ERR!   purescript-ast     > [11 of 22] Compiling Language.PureScript.AST.Literals
npm ERR!   purescript-ast     > [12 of 22] Compiling Language.PureScript.Roles
npm ERR!   purescript-ast     > [13 of 22] Compiling Language.PureScript.Traversals
npm ERR!   purescript-ast     > [14 of 22] Compiling Language.PureScript.Types
npm ERR!   purescript-ast     > [15 of 22] Compiling Language.PureScript.TypeClassDictionaries
npm ERR!   purescript-ast     > [16 of 22] Compiling Language.PureScript.Environment
npm ERR!   purescript-ast     > [17 of 22] Compiling Language.PureScript.AST.Binders
npm ERR!   purescript-ast     > [18 of 22] Compiling Language.PureScript.AST.Declarations
npm ERR!   purescript-ast     > [19 of 22] Compiling Language.PureScript.AST.Traversals
npm ERR!   purescript-ast     > [20 of 22] Compiling Language.PureScript.AST.Exported
npm ERR!   purescript-ast     > [21 of 22] Compiling Language.PureScript.AST
npm ERR!   purescript-ast     > [22 of 22] Compiling Paths_purescript_ast
npm ERR!   purescript-ast     > copy/register
npm ERR!   purescript-ast     > Installing library in /tmp/node-purescript-nh7xGI/.stack-work/install/x86_64-linux-tinfo6/52ee5b1a7abe325401dec9f2c740f7b25e4ae8e2ec8df1bd56792c1cd1db05a0/8.6.5/lib/x86_64-linux-ghc-8.6.5/purescript-ast-0.1.0.0-Gtmwmu4N43KCxo7Qi9BiwQ
npm ERR!   purescript-ast     > Registering library for purescript-ast-0.1.0.0..
npm ERR!   --  While building package language-javascript-0.7.0.0 (scroll up to its section to see the error) using:
npm ERR!         /home/pixtum/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 build --ghc-options ""
npm ERR!       Process exited with code: ExitFailure 1
npm ERR! [ FAILURE ] Build a binary from source (60s)
npm ERR! Error: Command failed with exit code 1 (EPERM): stack --allow-different-user install --local-bin-path=/home/pixtum/.npm-global/lib/node_modules/purescript --flag=purescript:RELEASE
npm ERR!     at makeError (/home/pixtum/.npm-global/lib/node_modules/purescript/node_modules/execa/lib/error.js:59:11)
npm ERR!     at handlePromise (/home/pixtum/.npm-global/lib/node_modules/purescript/node_modules/execa/index.js:112:26)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:94:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pixtum/.npm/_logs/2021-03-14T19_10_36_951Z-debug.log
```
yarn global add purescript 
```
yarn global v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/3] ⠂ purescript
[-/3] ⠂ waiting...
error /home/pixtum/.config/yarn/global/node_modules/purescript: Command failed.
Exit code: 1
Command: install-purescript --purs-ver=0.14.0
Arguments:
Directory: /home/pixtum/.config/yarn/global/node_modules/purescript
Output:
[ SUCCESS ] Check if a prebuilt 0.14.0 binary is provided for linux (526ms)
[ SUCCESS ] Download the prebuilt PureScript binary (1s)
[ FAILURE ] Verify the prebuilt binary works correctly
Error: Command failed: /home/pixtum/.config/yarn/global/node_modules/purescript/purs.bin --version
/home/pixtum/.config/yarn/global/node_modules/purescript/purs.bin: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

    at ChildProcess.exithandler (node:child_process:326:12)
    at ChildProcess.emit (node:events:378:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Socket.<anonymous> (node:internal/child_process:453:11)
    at Socket.emit (node:events:378:20)
    at Pipe.<anonymous> (node:net:665:12)

↓ Fallback: building from source

[ SUCCESS ] Check if 'stack' command is available
[ SUCCESS ] Download the PureScript 0.14.0 source (928ms)
[ RUNNING ] command: stack setup
  Specified file "README.md" for extra-source-files does not exist
  Specified file "INSTALL.md" for extra-source-files does not exist
  Specified file "CONTRIBUTORS.md" for extra-source-files does not exist
  Specified file "CONTRIBUTING.md" for extra-source-files does not exist
  Specified file "README.md" for extra-source-files does not exist
  Specified file "README.md" for extra-source-files does not exist
  stack will use a sandboxed GHC it installed
  For more information on paths, see 'stack path' and 'stack exec env'
  To use this GHC and packages outside of a project, consider using:
  stack ghc, stack ghci, stack runghc, or stack exec
[ SUCCESS ] Ensure the appropriate GHC is installed (1s)
[ RUNNING ] command: stack install --local-bin-path=/home/pixtum/.config/yarn/global/node_modules/purescript --flag=purescript:RELEASE
  Specified file "README.md" for extra-source-files does not exist
  Specified file "INSTALL.md" for extra-source-files does not exist
  Specified file "CONTRIBUTORS.md" for extra-source-files does not exist
  Specified file "CONTRIBUTING.md" for extra-source-files does not exist
  Specified file "README.md" for extra-source-files does not exist
  Specified file "README.md" for extra-source-files does not exist
  purescript-ast     > configure (lib)
  purescript-ast     > Configuring purescript-ast-0.1.0.0...
  language-javascript> configure
  purescript-ast     > build (lib)
  purescript-ast     > Preprocessing library for purescript-ast-0.1.0.0..
  purescript-ast     > Building library for purescript-ast-0.1.0.0..
  purescript-ast     > [ 1 of 22] Compiling Control.Monad.Supply
  purescript-ast     > [ 2 of 22] Compiling Control.Monad.Supply.Class
  language-javascript> Configuring language-javascript-0.7.0.0...
  purescript-ast     > [ 3 of 22] Compiling Language.PureScript.Comments
  language-javascript> build
  language-javascript> Preprocessing library for language-javascript-0.7.0.0..
  language-javascript> happy: src/Language/JavaScript/Parser/Grammar7.y: hGetContents: invalid argument (invalid byte sequence)
  purescript-ast     > [ 4 of 22] Compiling Language.PureScript.AST.SourcePos
  purescript-ast     > [ 5 of 22] Compiling Language.PureScript.Crash
  purescript-ast     > [ 6 of 22] Compiling Language.PureScript.AST.Operators
  purescript-ast     > [ 7 of 22] Compiling Language.PureScript.Names
  purescript-ast     > [ 8 of 22] Compiling Language.PureScript.Constants.Prim
  purescript-ast     > [ 9 of 22] Compiling Language.PureScript.PSString
  purescript-ast     > [10 of 22] Compiling Language.PureScript.Label
  purescript-ast     > [11 of 22] Compiling Language.PureScript.AST.Literals
  purescript-ast     > [12 of 22] Compiling Language.PureScript.Roles
  purescript-ast     > [13 of 22] Compiling Language.PureScript.Traversals
  purescript-ast     > [14 of 22] Compiling Language.PureScript.Types
  purescript-ast     > [15 of 22] Compiling Language.PureScript.TypeClassDictionaries
  purescript-ast     > [16 of 22] Compiling Language.PureScript.Environment
  purescript-ast     > [17 of 22] Compiling Language.PureScript.AST.Binders
  purescript-ast     > [18 of 22] Compiling Language.PureScript.AST.Declarations
  purescript-ast     > [19 of 22] Compiling Language.PureScript.AST.Traversals
  purescript-ast     > [20 of 22] Compiling Language.PureScript.AST.Exported
  purescript-ast     > [21 of 22] Compiling Language.PureScript.AST
  purescript-ast     > [22 of 22] Compiling Paths_purescript_ast
  purescript-ast     > copy/register
  purescript-ast     > Installing library in /tmp/node-purescript-8ah8Tk/.stack-work/install/x86_64-linux-tinfo6/52ee5b1a7abe325401dec9f2c740f7b25e4ae8e2ec8df1bd56792c1cd1db05a0/8.6.5/lib/x86_64-linux-ghc-8.6.5/purescript-ast-0.1.0.0-Gtmwmu4N43KCxo7Qi9BiwQ
  purescript-ast     > Registering library for purescript-ast-0.1.0.0..
  --  While building package language-javascript-0.7.0.0 (scroll up to its section to see the error) using:
        /home/pixtum/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 build --ghc-options ""
      Process exited with code: ExitFailure 1
[ FAILURE ] Build a binary from source (60s)
Error: Command failed with exit code 1 (EPERM): stack --allow-different-user install --local-bin-path=/home/pixtum/.config/yarn/global/node_modules/purescript --flag=purescript:RELEASE
    at makeError (/home/pixtum/.config/yarn/global/node_modules/purescript-installer/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/pixtum/.config/yarn/global/node_modules/purescript-installer/node_modules/execa/index.js:112:26)
```

## To Reproduce

run either yarn global add purescript or npm install -g purescript on artix linux

## Expected behavior

install the purs binary

**Comment by hdgarrood** [comment]
If you install the libtinfo or ncurses package for your platform, the prebuilt binaries might work (depending on what version your distro bundles), but in any case building from source definitely should. It looks like you also need to set a locale from the happy error - I think `export LANG=en_US.UTF-8` should do it.

**Comment by WilliamBehrens** [comment]
@hdgarrood I have ncurses installed, what's the name for libtinfo in the arch repos?

**Comment by rhendric** [comment]
libtinfo is part of the `ncurses` package. On Arch, you may want to use the `ncurses5-compat-libs` AUR package, which adds support for the older libraries expected by the prebuilt binaries. (This shouldn't prevent building from source though.)

**Comment by WilliamBehrens** [comment]
Ok it did appear to be purely due to the export lang issue that @hdgarrood mentioned, I got it installed
