### ISSUE TITLE
genericShow compiles to invalid Javascript for records when a constructor in the same module is named Prim

### ISSUE THREAD

**Issue by colinlogue** [purescript/purescript#4229]
## Description

A module that has a data definition with a constructor named `Prim` and a record in a type that uses `genericShow` will throw `ReferenceError: Prim_1 is not defined` at runtime.

## To Reproduce

Start a new project with `spago init`. Replace `src/Main.purs` with the following:
```
module Main where

import Prelude

import Data.Generic.Rep (class Generic)
import Data.Show.Generic (genericShow)
import Effect (Effect)
import Effect.Console (log)

data X a = Prim { y :: a }

derive instance Generic (X a) _
instance Show a => Show (X a) where
  show x = genericShow x

main :: Effect Unit
main = do
  log $ show $ Prim { y : 1 }
```

Run the program with `spago run`.

On my machine, this created the following output:
```
[info] Build succeeded.
C:\Users\colin\Documents\Projects\purescript-show-error\output\Main\index.js:25
            return Data_Show_Generic.genericShow(genericX_)(Data_Show_Generic.genericShowConstructor(Data_Show_Generic.genericShowArgsArgument(Data_Show.showRecord(Prim_1["undefined"])(Data_Show.showRecordFieldsCons({
                                                                                                                             
                                       ^

ReferenceError: Prim_1 is not defined
    at show (C:\Users\colin\Documents\Projects\purescript-show-error\output\Main\index.js:25:165)
    at Object.<anonymous> (C:\Users\colin\Documents\Projects\purescript-show-error\output\Main\index.js:37:71)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\colin\Documents\Projects\purescript-show-error\.spago\run.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
[error] Running failed; exit code: 1
```

## Expected behavior

The program should output `(Prim { y: 1 })` to the console.

## Additional context

Running on Windows 11, haven't checked on other platforms.

## PureScript version

0.14.5

**Comment by PureFunctor** [comment]
This seems to be related to #4188. I think happens here is that the `Prim` constructor is an `Ident`, and it gets caught by the renaming routine during code generation. `Prim` is never introduced by a `require` so I think it shouldn't be affected.

Here's a potential minimal fix:
```diff
@@ -105,9 +107,11 @@ moduleToJs (Module _ coms mn _ imps exps reExps foreigns decls) foreign_ =
   renameImports = go M.empty
     where
     go :: M.Map ModuleName (Ann, ModuleName) -> [Ident] -> [(Ann, ModuleName)] -> M.Map ModuleName (Ann, ModuleName)
-    go acc used ((ann, mn') : mns') =
+    go acc used ((ann, mn') : mns')
+      | C.Prim == mn' = go (M.insert mn' (ann, mn') acc) used mns'
+      | otherwise =
       let mni = Ident $ moduleNameToJs mn'
       in if mn' /= mn && mni `elem` used
          then let newName = freshModuleName 1 mn' used
               in go (M.insert mn' (ann, newName) acc) (Ident (runModuleName newName) : used) mns'
          else go (M.insert mn' (ann, mn') acc) used mns'
```
