### ISSUE TITLE
Website is blank unless I rename a module

### ISSUE THREAD

**Issue by abigailalice** [purescript/purescript#4346]
## Description

I've been using Purescript to build a website and came across a super peculiar bug where sometimes when I try to view my website the page is blank, and after commenting out different portions of the source I eventually narrowed it down to a single module. Attempting to use any identifier from this module causes the issue, no matter what it is. Bizarrely, simply renaming the module fixed the issue.

## To Reproduce

I'm not sure how to come up with a minimal example of the behaviour outside of my own environment, as it seems to occur even if the module is empty except for a single integer which it exports. At least in my own code base all I need to do is rename the module back to the problematic name, and it immediately returns, while changing it to a different name again fixes the issue, very consistently, so I'm at least confident that I can reproduce it myself. The file name itself doesn't appear to cause any change in behaviour, only the name declared with the `module` keyword. My best guess is maybe there's some buggy cached compiler artifact that gets picked up, because otherwise I'm stumped; I spent about a day trying to figure out if there was an infinite loop in the module, before figuring out literally anything inside it would trigger it.

## Expected behavior

Module names shouldn't be semantically relevant.

## Additional context

The name of the module is `FlashQuiz.Components.DropDown` in the unlikely case of a bug that actually makes module names semantically relevant. Changing it to `FlashQuiz.Components.DropDown2` was the fix. 

## PureScript version

0.14.2

**Comment by rhendric** [comment]
Do you get any error messages in the console when the page is blank?

**Comment by abigailalice** [comment]
I get

```
index.js:46768 Uncaught ReferenceError: require is not defined
    at index.js:46768:38
    at index.js:46887:3
(anonymous) @ index.js:46768
(anonymous) @ index.js:46887
```

**Comment by rhendric** [comment]
Did you by chance change compiler versions at some point during development?

Does deleting your `output` directory and recompiling resolve the issue?

**Comment by abigailalice** [comment]
That did seem to fix it. I'm not sure if I ever did change versions, though I don't have a great mental model of the purescript tool stack, so I may have inadvertently.

**Comment by rhendric** [comment]
@purescript/compiler Should we add the compiler version to the cache and invalidate it if it's ever different from the current version? I thought I remembered reading this as a proposal somewhere but I can't seem to find it now.

**Comment by garyb** [comment]
That sounds like a good idea to me. And yeah, it seems like something we would have talked about in the past!
