### ISSUE TITLE
Cannot install on docker image node:18 --platform=linux/x86_64

### ISSUE THREAD

**Issue by hedefalk** [purescript/purescript#4481]
## Description
I cannot install on a node:18 on linux/x86_64

## To Reproduce

Dockerfile_Purescript_Install_Issue:
```
FROM node:18 as build 
WORKDIR /app
RUN npm install --save-dev purescript
```

Run:

```
docker build . -f ./Dockerfile_Purescript_Install_Issue --platform=linux/x86_64
```

## Expected behavior
Working image

## Actual behavior
```
> [3/3] RUN npm install --save-dev purescript:                                                                                 
#0 12.97 npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs                           
#0 26.99 npm notice                                                                                                             
#0 26.99 npm notice New minor version of npm available! 9.5.1 -> 9.7.2                                                          
#0 26.99 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.2>                                                 
#0 26.99 npm notice Run `npm install -g npm@9.7.2` to update!
#0 26.99 npm notice 
#0 27.01 npm ERR! code 1
#0 27.01 npm ERR! path /app/node_modules/purescript
#0 27.02 npm ERR! command failed
#0 27.02 npm ERR! command sh -c install-purescript --purs-ver=0.15.9
#0 27.03 npm ERR! [ SUCCESS ] Check if a prebuilt 0.15.9 binary is provided for linux-x86_64 (945ms)
#0 27.03 npm ERR! [ SUCCESS ] Download the prebuilt PureScript binary (1s)
#0 27.03 npm ERR! [ FAILURE ] Verify the prebuilt binary works correctly (8s)
#0 27.03 npm ERR! Error: Command failed: /app/node_modules/purescript/purs.bin --version
#0 27.03 npm ERR! 
#0 27.03 npm ERR!     at ChildProcess.exithandler (node:child_process:419:12)
#0 27.03 npm ERR!     at ChildProcess.emit (node:events:513:28)
#0 27.03 npm ERR!     at maybeClose (node:internal/child_process:1091:16)
#0 27.03 npm ERR!     at Socket.<anonymous> (node:internal/child_process:449:11)
#0 27.03 npm ERR!     at Socket.emit (node:events:513:28)
#0 27.03 npm ERR!     at Pipe.<anonymous> (node:net:322:12)
#0 27.03 npm ERR! 
#0 27.03 npm ERR! See troubleshooting suggestions in https://github.com/purescript/purescript/blob/master/INSTALL.md
#0 27.03 npm ERR! 
#0 27.03 npm ERR! ↓ Fallback: building from source
#0 27.03 npm ERR! 
#0 27.03 npm ERR! [ FAILURE ] Check if 'stack' command is available
#0 27.03 npm ERR! Error: Command failed with exit code 2 (ENOENT): stack --allow-different-user --numeric-version
#0 27.03 npm ERR! spawn stack ENOENT
#0 27.03 npm ERR!     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
#0 27.03 npm ERR!     at onErrorNT (node:internal/child_process:476:16)
#0 27.03 npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
#0 27.03 npm ERR! 
#0 27.03 npm ERR! See troubleshooting suggestions in https://github.com/purescript/purescript/blob/master/INSTALL.md
#0 27.04 
#0 27.04 npm ERR! A complete log of this run can be found in:
#0 27.04 npm ERR!     /root/.npm/_logs/2023-06-29T14_52_35_174Z-debug-0.log
------
Dockerfile_Purescript:3
--------------------
   1 |     FROM node:18 as build 
   2 |     WORKDIR /app
   3 | >>> RUN npm install --save-dev purescript
--------------------
ERROR: failed to solve: process "/bin/sh -c npm install --save-dev purescript" did not complete successfully: exit code: 1
```

## Additional context
These all works fine. I'm on a Mac and my default arch is aarch64 I guess and they all get the same image docker.io/library/node:18@sha256:19892542dd80e33aec50a51619ab36db0921de240c6a4ff6024d801f84881293:

```
docker build . -f ./Dockerfile_Purescript_Install_Issue
docker build . -f ./Dockerfile_Purescript_Install_Issue --platform=linux/arm64/v8
docker build . -f ./Dockerfile_Purescript_Install_Issue --platform=linux/aarch64 
```

## PureScript version

0.15.9

**Comment by hedefalk** [comment]
Weird, I get other errors if I use docker run instead of a Dockerfile to build:

```
✗ docker run -it --platform=linux/x86_64 node:18 sh
# mkdir app
# cd app
# npm install --save-dev purescript
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.7.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.2
npm notice Run npm install -g npm@9.7.2 to update!
npm notice 
npm ERR! code 1
npm ERR! path /app/node_modules/purescript
npm ERR! command failed
npm ERR! command sh -c install-purescript --purs-ver=0.15.9
npm ERR! [ FAILURE ] Check if a prebuilt 0.15.9 binary is provided for linux-x86_64 (2s)
npm ERR! Error: 503 Backend unavailable, connection timeout
npm ERR!     at /app/node_modules/purescript-installer/dl-tar/index.js:193:13
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async /app/node_modules/purescript-installer/dl-tar/index.js:190:17
npm ERR! 
npm ERR! See troubleshooting suggestions in https://github.com/purescript/purescript/blob/master/INSTALL.md

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-06-29T18_02_19_803Z-debug-0.log





# tail -50 /root/.npm/_logs/2023-06-29T18_02_19_803Z-debug-0.log
1257 timing build:link:node_modules/purescript Completed in 17ms
1258 timing build:link:node_modules/purescript-installer Completed in 16ms
1259 timing build:link:node_modules/which Completed in 15ms
1260 timing build:link:node_modules/rimraf Completed in 16ms
1261 timing build:link:node_modules/semver Completed in 15ms
1262 timing build:link:node_modules/@npmcli/move-file/node_modules/rimraf Completed in 15ms
1263 timing build:link:node_modules/make-fetch-happen/node_modules/rimraf Completed in 14ms
1264 timing build:link Completed in 21ms
1265 info run purescript@0.15.9 postinstall node_modules/purescript install-purescript --purs-ver=0.15.9
1266 info run purescript@0.15.9 postinstall { code: 1, signal: null }
1267 timing reify:rollback:createSparse Completed in 211ms
1268 timing reify:rollback:retireShallow Completed in 0ms
1269 timing command:install Completed in 21595ms
1270 notice
1270 notice New minor version of npm available! 9.5.1 -> 9.7.2
1270 notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.2
1270 notice Run npm install -g npm@9.7.2 to update!
1270 notice
1271 verbose stack Error: command failed
1271 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
1271 verbose stack     at ChildProcess.emit (node:events:513:28)
1271 verbose stack     at maybeClose (node:internal/child_process:1091:16)
1271 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
1272 verbose pkgid purescript@0.15.9
1273 verbose cwd /app
1274 verbose Linux 5.15.49-linuxkit-pr
1275 verbose node v18.16.1
1276 verbose npm  v9.5.1
1277 error code 1
1278 error path /app/node_modules/purescript
1279 error command failed
1280 error command sh -c install-purescript --purs-ver=0.15.9
1281 error [ FAILURE ] Check if a prebuilt 0.15.9 binary is provided for linux-x86_64 (2s)
1281 error Error: 503 Backend unavailable, connection timeout
1281 error     at /app/node_modules/purescript-installer/dl-tar/index.js:193:13
1281 error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1281 error     at async /app/node_modules/purescript-installer/dl-tar/index.js:190:17
1281 error
1281 error See troubleshooting suggestions in https://github.com/purescript/purescript/blob/master/INSTALL.md
1282 verbose exit 1
1283 timing npm Completed in 21774ms
1284 verbose unfinished npm timer reify 1688061739976
1285 verbose unfinished npm timer reify:build 1688061751202
1286 verbose unfinished npm timer build 1688061751206
1287 verbose unfinished npm timer build:deps 1688061751208
1288 verbose unfinished npm timer build:run:postinstall 1688061751266
1289 verbose unfinished npm timer build:run:postinstall:node_modules/purescript 1688061751268
1290 verbose code 1
1291 error A complete log of this run can be found in:
1291 error     /root/.npm/_logs/2023-06-29T18_02_19_803Z-debug-0.log


```

Seems I now get this error for all architectures…

**Comment by hedefalk** [comment]
Ok, got it - its cached on the docker build but when I redid it with docker run I got new unfilled cache slots. Running the docker build with --no-cache fails on all architectures for me now.

```
#0 14.27 npm ERR! Error: 503 Backend unavailable, connection timeout
#0 14.27 npm ERR!     at /app/node_modules/purescript-installer/dl-tar/index.js:193:13
#0 14.27 npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
#0 14.27 npm ERR!     at async /app/node_modules/purescript-installer/dl-tar/index.js:190:17
```

**Comment by rhendric** [comment]
Can you reproduce this if you modify the npm install line to install PureScript 0.15.8? What about different versions of the Node image?

**Comment by hedefalk** [comment]
Yeah, same on 0.15.8 and older too. And node:14 as well. Trying commands like these now and everything fails with the same thing:

docker run -it --platform=linux/x86_64 node:14 sh -c "mkdir app; cd app; npm --version; npm install -D purescript@0.15.8"

docker run -it --platform=linux/x86_64 node:18 sh -c "mkdir app; cd app; npm --version; npm install -D purescript@0.15.8"

docker run -it --platform=linux/x86_64 node:14 sh -c "mkdir app; cd app; npm --version; npm install -D purescript@0.15.2"

```
✔ Check if a prebuilt 0.15.9 binary is provided for linux-x64 (1s)
✔ Download the prebuilt PureScript binary (1s)
✖ Verify the prebuilt binary works correctly (23s)
  /app/node_modules/purescript/purs.bin --version
  Error: Command failed: /app/node_modules/purescript/purs.bin --version
```

After that fails there is no purescript folder under node_modules anymore - I guess it reverts…?  And then there's the stack fallback, but this image doesn't have any stack.

Is there some online store that simply is down?

**Comment by rhendric** [comment]
If you're getting `✔ Check if a prebuilt 0.15.9 binary is provided for linux-x64 (1s)` when you try to install a version that *isn't* 0.15.9, something is odd. Is that the case?

I tried your original Docker file and it worked as expected, though my native architecture is x86_64. Still, that suggests to me that there isn't a global connectivity issue, though you might have a local one.

**Comment by hedefalk** [comment]
>If you're getting ✔ Check if a prebuilt 0.15.9 binary is provided for linux-x64 (1s) when you try to install a version that isn't 0.15.9, something is odd. Is that the case?

No, sorry for the ordering - that was the log for node:0.14 and purescript@0.15.9. But they're basically all the same:

```
✗ docker run -it --platform=linux/x86_64 node:14 sh -c "mkdir app; cd app; npm --version; npm install -D purescript@0.15.2"
6.14.18
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> purescript@0.15.2 postinstall /app/node_modules/purescript
> install-purescript --purs-ver=0.15.2

✔ Check if a prebuilt 0.15.2 binary is provided for linux (1s)
✔ Download the prebuilt PureScript binary (1s)
✖ Verify the prebuilt binary works correctly (14s)
  /app/node_modules/purescript/purs.bin --version
  Error: Command failed: /app/node_modules/purescript/purs.bin --version

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
```

Yeah, I'm on darwin/aarch64 natively, but this docker desktop and hyperkit.

**Comment by rhendric** [comment]
If you `docker run -it --platform=linux/x86_64 node:18 bash`, and inside that shell:
* manually download and unpack https://github.com/purescript/purescript/releases/download/v0.15.9/linux64.tar.gz
* run `purescript/purs --version`

what happens?

**Comment by hedefalk** [comment]
Seems to work:

```
docker run -it --platform=linux/x86_64 node:18 bash

root@8b8d0980c30a:/# curl -L https://github.com/purescript/purescript/releases/download/v0.15.9/linux64.tar.gz | tar xz

root@8b8d0980c30a:/# purescript/purs --version
0.15.9
```

The purs --version takes quite some time though.

**Comment by hedefalk** [comment]
Comparing the purescript dists with spago it seems I might have the explaination to that. Spago just have "linux" and I guess that's x86/amd64?

<img width="685" alt="image" src="https://github.com/purescript/purescript/assets/116520/40d0d117-3f14-4509-9797-0a77bb682ffe">



<img width="702" alt="image" src="https://github.com/purescript/purescript/assets/116520/f1153811-3727-4957-a760-b49220d8476e">

**Comment by rhendric** [comment]
The Spago binaries are x86_64 only; you have to build Spago from source to get ARM binaries, unfortunately.

If the manually downloaded `purs` works in your Docker instance, then I think the next thing to check is that `npm install purescript` is getting the same binary. Can you compare `node_modules/purescript/purs.bin` to the downloaded binary and see if they match? If not, the PureScript NPM installer might be incorrectly downloading the ARM binary. If so... I'm honestly out of ideas; something would be unexpected about your Docker environment but I wouldn't know what to check next.

**Comment by hedefalk** [comment]
>Can you compare node_modules/purescript/purs.bin to the downloaded binary and see if they match?

Unfortunately there is no purescript there after the postinstall fails - I think npm install reverts?

Thanks for the help so far! I actually realize now that this road is somewhat of a deadend to me - I need to get an arm build of spago to work instead. But I'll try to revisit later if I find the time.

**Comment by f-f** [comment]
This question moved to https://github.com/purescript/spago/issues/968, which was resolved by switching to `spago@next`. Shall this be closed as well?
