### ISSUE TITLE
Runtime error when using `>>=` instead of `do`

### ISSUE THREAD

**Issue by pseudonom** [purescript/purescript#941]
```purescript

module Test.Main where

import Control.Bind
import Data.Maybe
import Debug.Trace
import Test.QuickCheck

newtype Prob = Prob Number
prob n | 0 <= n && n <= 1 = Just $ Prob n
prob _ | otherwise = Nothing

instance arbProb :: Arbitrary Prob where
  arbitrary = do
    p <- prob <$> arbitrary
    maybe arbitrary pure $ p

```

The above works fine. However, if we define the arbitrary instance with
```purescript
arbitrary = prob <$> arbitrary >>= maybe arbitrary pure
```
compiling and running results in

```
[stdin]:17336
        return dict.arbitrary;
                   ^
TypeError: Cannot read property 'arbitrary' of undefined
    at Object.PS.Test_QuickCheck.arbitrary ([stdin]:17336:20)
    at [stdin]:17558:131
    at [stdin]:17565:3
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at Socket.<anonymous> (node.js:154:11)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
```
.

The code generated in the first case is (the working `do` version) is:
```javascript
var arbProb = new Test_QuickCheck.Arbitrary(Prelude[">>="](Test_QuickCheck_Gen.bindGen)(Prelude["<$>"](Test_QuickCheck_Gen.functorGen)(prob)(Test_QuickCheck.arbitrary(Test_QuickCheck.arbNumber)))(function (_0) {
    return Data_Maybe.maybe(Test_QuickCheck.arbitrary(arbProb))(Prelude.pure(Test_QuickCheck_Gen.applicativeGen))(_0);
}));
```
.

The code generated in the second case is (the non-functional `>>=` version) is:
```javascript
var arbProb = new Test_QuickCheck.Arbitrary(Prelude[">>="](Test_QuickCheck_Gen.bindGen)(Prelude["<$>"](Test_QuickCheck_Gen.functorGen)(prob)(Test_QuickCheck.arbitrary(Test_QuickCheck.arbNumber)))(Data_Maybe.maybe(Test_QuickCheck.arbitrary(arbProb))(Prelude.pure(Test_QuickCheck_Gen.applicativeGen))));
```
.

So the problem is `arbProb`'s definition in terms of itself.

**Comment by joneshf** [comment]
Seems related to #365

**Comment by joneshf** [comment]
Seems like it's related to #365.

**Comment by paf31** [comment]
Yes it is. I'll close this as a duplicate.

**Comment by garyb** [comment]
Should we reopen #365 then?
